### ISSUE TITLE
Current build fails

### ISSUE THREAD

**Issue by Necrophagos** [Necrophagos/SF4ComboTrainer#15]
Unfortunately I cannot set my MS Visual Studio to English, so all the error messages are german and probably won't help you.

heres a quick manual summary
1. Warning: XInputDotNetPure is targeted at x86 processor architecture this may lead to errors
2. Warning: XInputDotNetPure Assembly not found
3. Error: ...\XInputDotNetPure.dll must be singned with a strong name ?!? whatever
4. Warning: XInputDotNetPure Assembly has different destination Processer architecture defined than project
5. - 10. Warning: Xceed.Wpf.AvalonDock/DataGrid/Toolkit stuff not found
6. Error: Tag IntegerUpDOwn not available in xml namespace (TimeLineItemDetail.xan : 37)

12-18 repeat of 5-10

edit: if you have trouble adding files espcially if they are inside one of the bin folders, check if they are not .gitignore ed

**Comment by thopiddock** [comment]
Is that happening after pulling the latest commit?

The Warnings are fine, they are from my input system but they don't affect
anything and you can safely ignore them. The Error on 3 is probably due to
a reference missing. Can you check your references and let me know if they
are showing XInputDotNetPure.dll.

Error on 5 - 10 will be the ExtendedWPFToolkit misbehaving, does the Xcede
reference resolve properly like XInput?

**Comment by Necrophagos** [comment]
okay the xinput reference does not resolve properly in sf4combotrainer, (yellow excl mark). but is doing fine in in the modelproject (but there is a lib folder inside the model project, that is not inside the sf4combotrainer)

in the view project all the xceed references have yellow exclamation marks

**Comment by cbcoolbox** [comment]
Sorry just move the DLL ( XInputDotNetPure.dll.) from the model project bin\debug into the sf4combotrainer project bin\debug and it will compile. You can't compile the whole solution without the xceed user controls.

**Comment by Necrophagos** [comment]
what is xceed? where do I get it from? can't it be added to the repository?
I'd wish for this code to build out of the box on a freshly installed ms vs express 2013 for desktop. is that possible?

**Comment by cbcoolbox** [comment]
All i know is xceed supplies 3rd party user controls for WPF. I thought you had to pay but there may be some free toolkit. I agree it'd be awesome to keep this all stock. Im sure @thopiddock has all the info.

**Comment by thopiddock** [comment]
It is all free for us to use. The toolkit enables a lot more flexibility on
controls and allows us to do a graphical timeline.

Xinput is an interface library that pulls the State data from XBox
controllers without taking exclusive control on them meaning we can record
data from inputs made by the player with our interruption in game.

These can be added to the lib folders but I simply miscompiled them earlier
today in a rush for work. The references for xcede can all be put in the
lib folder for View , the Xinput should be I  lib for Model with an
interface ref for Xinput in the root folder of Model .

**Comment by thopiddock** [comment]
OKAY! @Necrophagos  @cbcoolbox - this should fix #15: 

https://github.com/Necrophagos/SF4ComboTrainer/pull/16

Can you lads try pulling it again and checking it compiles nicely?

**Comment by Necrophagos** [comment]
it compiles now :)
as far as I understand the build process now automagically puts InputSimulator.dll in the build directories instead of my old manual (dumb) way. thats awesome. the same thing should happen to sf4keyboard.cfg
thx for your work. The WPF version of the is currently WIP right?

**Comment by cbcoolbox** [comment]
Thank you for fixing that.

**Comment by thopiddock** [comment]
No problem @cbcoolbox I was frantically trying to fix it all as I hate nothing more than a commit that doesn't build. Pet peeve and I try to avoid it where possible :D
