### ISSUE TITLE
Item Detail's Up/Down widget not disabled after playback

### ISSUE THREAD

**Issue by leemi** [Necrophagos/SF4ComboTrainer#18]
If the last timeline item is not a wait frame, the numeric up/down widget in Item Details should be disabled.

Steps to reproduce:
Load any combo
Ensure the last item is not a wait frame
play timeline

**Comment by thopiddock** [comment]
This could probably be countered by reselecting the last item in the list after enabling the controls from finishing playback. I'll take a look into it.
