### ISSUE TITLE
Remember settings

### ISSUE THREAD

**Issue by leemi** [Necrophagos/SF4ComboTrainer#19]
Settings (ie. SF4 Steam Version & Autoswitch) should be saved between launches.
The last loaded combo should be restored as well.

**Comment by thopiddock** [comment]
We can utilise the inbuilt project Settings to store and retrieve individual settings like these. For the files we can store the string of the last file path and attempt to load that upon form initialising.

**Comment by leemi** [comment]
We should be saving the combo to a file (lastcombo.cmb or something) every time the user makes a change. That way, if they accidentally close the app or it crashes, the combo is not lost.
