### ISSUE TITLE
To change Inputs or not to change Inputs

### ISSUE THREAD

**Issue by thopiddock** [Necrophagos/SF4ComboTrainer#25]
When using inputs in a game state the general idea is to store the button pressed and directions in a struct of bools (see TPInputLibrary SF4InputState.cs for general structure.) 

This Issue is more a proposition and idea rather than an issue - we should change the current input logic (several enumerations in an array of enums) to a struct of the Inputs like in SF4InputState so that we can better display the state of controls and bind the individual buttons presses to UI events on the forms we utilise.

This could help us create a visual cue as well as a sound to show what the button presses should look like by using the Form1.cs / MainWindow.xaml to display the state of each buttons struct value rather than looping the enumerations to check if it exists or not. It would also help with regards to tracking input Holds rather than just presses, by comparing prevState to the currentState.

Discuss?

**Comment by Necrophagos** [comment]
Hey Tom,

thx for your continous effort working on the project.
I haven't had much time to devote to the project lately as I was occupied with fixing my current unemployment situation. That worked out and I'll be starting my new job on monday. This also means that I currently have a huge amount of learning to do to get setteled in at my new job.

I'd suggest that if no one replies to the issues you opened you can always take matters into your own hands and make well judged decisions by yourself to prevent the progess from standing still.

If you are unsure about a decision you can also add feature branches that may or may not get merged back in in the future.

I hope that I soon have time to contribute again but until then I wanted to have you know why I am currently not doing anything.

**Comment by thopiddock** [comment]
Hey Necro,

Congratulations on the new job, I hope your start on Monday goes well.
Learn well and put the effort in, you'll do fine.

I'm consistently working on the tool, I haven't pushed the branch for a
while as I'm working on the UI sprite-map which will bind to the ViewModel,
no point in uploading the branch until it's functional! I'm working on any
issue that I can and updating when I can. Get yourself settled in the new
position and just add to the project when you can.
