### ISSUE TITLE
Crashing when starting combo

### ISSUE THREAD

**Issue by BuccoBruce** [Necrophagos/SF4ComboTrainer#30]
ISSUE: With a combo loaded, when pressing "Play" under TimeLine SF4ComboTrainer will freeze, nothing will happen in SF4, and SF4ComboTrainer will crash.

TROUBLESHOOTING:

I've downloaded multiple versions of SF4ComboTrainer, master edition and Jan132014 edition as well.

I have checked that my configuration buttons match the sf4keyboard config file.

I have checked that the stage is rendered on high rather than low.

Stage is training stage.  I have tried loading the Ryu FADC ultra combo and have tried loading a combo of my own with one move, just a neutral jab.

I have tried this in windowed and fullscreen mode.

I am on steam, SF4 Steam Version is checked.
Autoswitch to SF4 is checked.

My steam installation is not C:\Program Files(x86)..., it is D:\Games\Steam...

.NET Framework 4.5.2 installed.

Win7 64 installation

Any ideas?

**Comment by thopiddock** [comment]
This tool is now obsolete, please go to http://frametrapped.com and install the latest version.
